### ISSUE TITLE
[割り込みタスク] AmountBookService の JUnit テストに別戦略のテストを追加する

### ISSUE THREAD

**Issue by t-ita** [Ryoma137/okozukai#19]
AmountBookService テストは、Repository のテストと同様のテストでしたが、 `Stream::max` を使わなくてもできる戦略があるよ、という案がでたので、ひとつのプラクティスとして、テストメソッドの追加をお願いします。

具体的には、データが追加されていること・既存データに影響しないことを確認する下記メソッドを追加してください。
戦略は、日本語コメントで記載されているので、コメントに従う形で実装してください。

```Java
    @Test
    @Sql("/test-schema.sql")
    @DisplayName("registerIncome_既存データあり_データが追加され既存データに変更なし")
    void testRegisterIncome1() {
        // 1. DBに入っているデータを {Key: Id, Value: Account} のMap形式で保持する
        // 2. テスト対象メソッドにわたす値の生成
        // 3. テスト対象実行
        // 4. DBに入っているデータを {Key: Id, Value: Account} のMap形式で保持する
        // 5. 1.で取得したMapのデータが4.で取得したMapに存在していて、Valueの値も一致していること
        // 6. 4.で取得したMapに新しいIDをもつ値が存在していて、Valueの値が2.で生成した値と一致していること
    }
```

なお、作業対象となるブランチは、今PR中の [createAccountBookService](https://github.com/Ryoma137/okozukai/tree/createAccountBookService) でお願いします。

**Comment by Ryoma137** [comment]
[割り込みタスク] AmountBookService の JUnit テストに別戦略のテストを追加する 着手開始
予定時間（見積り）時間 : 2.5h

**Comment by Ryoma137** [comment]
18時ごろから離席していました。
AmountBookService の JUnit テストに別戦略のテストを追加する。再開します。

**Comment by Ryoma137** [comment]
[割り込みタスク] AmountBookService の JUnit テストに別戦略のテストを追加する 着手終了
予定時間（見積り）時間 : 2.5h
実働時間 4.5h
