### ISSUE TITLE
Account テーブルの操作を担うAccountRepository インターフェースを作成する

### ISSUE THREAD

**Issue by Ryoma137** [Ryoma137/okozukai#4]
## 説明
   Spring DATA JPA の CRUDRepository を継承した AccountRepository インターフェースを作成する。
JUnit テストも実装するが、この段階では登録のテストだけで構わない。

## 完了条件

- [x]  AccountRepository インターフェースが存在すること
- [x] AccountRepository インターフェースは CRUDRepository を継承していること
- [x] AccountRepository の JUnit テストが存在すること
- [x] 上記 JUnit テストはレビューされてテストケースに問題が無いこと
- [x] 上記 JUnit テストが完了していること

## プロダクトバックログ
　利用者が収入情報を登録できるようにする

**Comment by Ryoma137** [comment]
Account テーブルの操作を担うAccountRepository インターフェースを作成する Account テーブルの操作を担うAccountRepository インターフェースを作成する着手開始
予定時間（見積り）時間 : 1.5h

**Comment by Ryoma137** [comment]
test用にsqlを作成。
以前若杉さんから指摘された事を参考に、`TRUNCATE`でテーブルデータを削除するのではなく、テーブルそのものを一旦削除し、再生成するために以下のsql文を追加すると、日付のカラムがないとエラーになる(`Column "ITEM_DATE" not found;`)が、発生する。
` itemDate DATE`で日付のカラムを追加していると認識しているが間違っている？

`DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT (id bigint generated BY DEFAULT AS IDENTITY, itemDate DATE,  item VARCHAR(255), income INTEGER NOT NULL,expense INTEGER NOT NULL,  note VARCHAR(255),PRIMARY KEY (id));`

**Comment by Ryoma137** [comment]
`@GeneratedValue(strategy = GenerationType.IDENTITY)`から `@GeneratedValue(strategy = GenerationType.AUTO)` に変更するとidが重複するエラーが発生。
`@GeneratedValue(strategy = GenerationType.AUTO)`はデータベースごとに最も適切な手順を選択して，プライマリキー値を生成すると書いているが、h2のデータベースではどの様な振る舞いをしているかわからないので調査中。

@GeneratedValue
https://itpfdoc.hitachi.co.jp/manuals/link/cosmi_v0870/APR4/EU260072.HTM

**Comment by t-ita** [comment]
@Ryoma137 JUnit テストでエラーになっている感じですか？どのようなコードで、いつエラーになってます？

**Comment by t-ita** [comment]
@Ryoma137 私が勘違いしているかもしれないので、GenerationType.IDENTITY で行っても構いません（ここは特に重要ではないので）

**Comment by Ryoma137** [comment]
Account テーブルの操作を担うAccountRepository インターフェースを作成する Account テーブルの操作を担うAccountRepository インターフェースを作成する　着手終了
予定時間（見積り）時間 : 1.5h
実動時間 2.5h

**Comment by Ryoma137** [comment]
merge済
