### ISSUE TITLE
画面へのリンク先が `http://localhost:8080` になっている問題の修正

### ISSUE THREAD

**Issue by t-ita** [Ryoma137/okozukai#42]
- トップページから登録画面へのリンク
- 登録画面からトップページに戻るリンク

上記リンクの参照先が、`http://localhost:8080` が名指しされているので、サービスを公開した場合にリンクが切れてしまいます。

修正をお願いします。

**Comment by Ryoma137** [comment]
`http://localhost:8080` でのURLの名指しを修正しました。

**Comment by Ryoma137** [comment]
merge済
