### ISSUE TITLE
(Fix) 利用者が収支情報を編集できるようにする

### ISSUE THREAD

**Issue by Ryoma137** [Ryoma137/okozukai#46]
- [x] 画面表示時、指定したIDの収支情報がすでに入力されていること
- [x] accountBookServiceにaccountRepositoryからfindByIdを呼び出す`getById`メソッドを作成
- [x] getByIdのJunitテストの作成
- [x] AccountBookController内のgetUpdatePageメソッドにaccountBookService.getById()の変数`recordData`を追加し、各fieldに`recordData`の各値をset
- [x] 結合テスト

**Comment by t-ita** [comment]
@Ryoma137 この修正を実装するにあたって、やらなければならないタスク（スプリントバックログ）を検討して、この ISSUE の概要にチェックボックスで記載するようにしてください。

**Comment by Ryoma137** [comment]
merge済
